name: CI

on:
  push:
    branches: [main, dev, features]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0'
    - run: dotnet build PandaDaw.sln
    - run: dotnet publish -c Release -o ./publish

